WITH CET AS (
    SELECT 
      TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
      DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
      DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY_STARTED_AT,
      HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    --   CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun') then 'WEEKEND' else 'BUSINESSDAY' end as DAY_TYPE,
      {{DAY_TYPE('STARTED_AT')}} AS DAY_TYPE,
      MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT,
    --   CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2) THEN 'WINTER'
    --   WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5) THEN 'SPRING'
    --   WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8) THEN 'SUMMER'
    --   WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (9,10,11) THEN 'AUTUMN'
    --   END AS SEASON
    {{station_of_year('STARTED_AT')}} AS SEASON
    FROM {{ref('stg_bike')}}
)
SELECT * FROM CET